implemented correct return codes for runtests

diff --git a/src/runtests b/src/runtests
--- a/src/runtests
+++ b/src/runtests
@@ -1,3 +1,9 @@
 #!/bin/bash
-# Any output on stdout indicates failure
-diff test_assets/image.pnm <(./unittest)
+
+#exit code 0 indicates success, 1 indicates failure
+
+if [[ $(diff test_assets/image.pnm <(./unittest)) ]]; then
+    exit 1
+else
+    exit 0
+fi
